from __future__ import annotations

from dataclasses import dataclass, field
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from norn.profiles import SessionProfile


def _default_event_sink() -> Any:
    """Lazy factory so models.py has no hard dep on event_sink at import time."""
    from norn.event_sink import NullSink  # noqa: PLC0415

    return NullSink()


def _default_input_responder() -> Any:
    """Lazy factory so models.py has no hard dep on responder at import time."""
    from norn.responder import CLIResponder  # noqa: PLC0415

    return CLIResponder()


@dataclass
class UsageRecord:
    """Token and cost usage for a single Generate stage invocation.

    Populated from the SDK's ``ResultMessage`` after each agent call.
    Stored on ``StageResult.usage`` and accumulated by ``UsageTracker``.

    Attributes:
        stage_name: Name of the stage that produced this record.
        session_id: Claude session ID from the SDK.
        input_tokens: Tokens sent to the model.
        output_tokens: Tokens generated by the model.
        cache_read_input_tokens: Tokens read from the prompt cache.
        cache_creation_input_tokens: Tokens written to the prompt cache.
        total_cost_usd: Dollar cost for this call.
        duration_ms: Wall-clock time including tool execution.
        duration_api_ms: Time spent in API calls only.
        num_turns: Number of conversation turns in this call.
        is_error: ``True`` if the SDK reported an error.
        attempt: Loop attempt number (1-based) for retry tracking.
        model: Model shorthand or ID used for this call.
    """

    stage_name: str
    session_id: str | None = None
    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_input_tokens: int = 0
    cache_creation_input_tokens: int = 0
    total_cost_usd: float = 0.0
    duration_ms: int = 0
    duration_api_ms: int = 0
    num_turns: int = 0
    is_error: bool = False
    attempt: int = 1
    model: str | None = None
    provider: str | None = None

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass
class UsageTracker:
    """Accumulates UsageRecords across an entire pipeline run.

    Lives on ``PipelineContext.usage_tracker``. Records are added after each
    Generate stage completes. Provides aggregate properties for the usage
    report and budget checks.
    """

    records: list[UsageRecord] = field(default_factory=list)

    def add(self, record: UsageRecord) -> None:
        self.records.append(record)

    @property
    def total_input_tokens(self) -> int:
        return sum(r.input_tokens for r in self.records)

    @property
    def total_output_tokens(self) -> int:
        return sum(r.output_tokens for r in self.records)

    @property
    def total_tokens(self) -> int:
        return self.total_input_tokens + self.total_output_tokens

    @property
    def total_cache_read_tokens(self) -> int:
        return sum(r.cache_read_input_tokens for r in self.records)

    @property
    def total_cache_creation_tokens(self) -> int:
        return sum(r.cache_creation_input_tokens for r in self.records)

    @property
    def total_cost_usd(self) -> float:
        return sum(r.total_cost_usd for r in self.records)

    @property
    def total_duration_ms(self) -> int:
        return sum(r.duration_ms for r in self.records)

    @property
    def total_api_duration_ms(self) -> int:
        return sum(r.duration_api_ms for r in self.records)

    @property
    def unique_sessions(self) -> int:
        return len({r.session_id for r in self.records if r.session_id})

    @property
    def total_turns(self) -> int:
        return sum(r.num_turns for r in self.records)

    @property
    def last_session_id(self) -> str | None:
        """Return the most recent session_id from usage records."""
        for r in reversed(self.records):
            if r.session_id:
                return r.session_id
        return None


@dataclass
class StageLogEntry:
    """Detailed record for a single stage event within a pipeline run.

    Captures every executed, skipped, or cached stage so completed runs can be
    inspected later with the same step-level cost context shown during live
    output.
    """

    name: str
    status: str
    success: bool
    attempt: int = 1
    duration_ms: int = 0
    cost_usd: float = 0.0
    running_total_cost_usd: float = 0.0
    running_total_tokens: int = 0
    input_tokens: int = 0
    output_tokens: int = 0
    cache_read_input_tokens: int = 0
    cache_creation_input_tokens: int = 0
    duration_api_ms: int = 0
    num_turns: int = 0
    model: str | None = None
    session_id: str | None = None
    error: str | None = None
    provider: str | None = None

    @property
    def total_tokens(self) -> int:
        return self.input_tokens + self.output_tokens


@dataclass
class StageResult:
    """Result returned by a stage after execution.

    Every stage ``run()`` method returns a ``StageResult``. The runner stores
    it on ``PipelineContext.results[stage_name]`` so downstream stages can
    access prior outputs via ``ctx.get("stage_name")``.

    Attributes:
        name: Stage name (set by the runner after ``run()`` returns).
        success: ``True`` if the stage completed without error.
        output: Arbitrary stage output — file contents, command output dict,
            generated code, or structured JSON from a template.
        error: Error message when ``success=False``.
        usage: Token/cost usage record (only for Generate stages).
        artifacts: File paths created or modified by the agent.
    """

    name: str
    success: bool
    output: Any = None
    error: str | None = None
    usage: UsageRecord | None = None
    artifacts: list[str] = field(default_factory=list)


@dataclass
class PipelineContext:
    """Mutable state carried through an entire pipeline execution.

    Created by the runner at pipeline start and passed to every stage's
    ``run()`` method. Stages read prior outputs via ``ctx.get("name")``
    and the runner writes results after each stage completes.

    Attributes:
        results: Stage results keyed by stage name.
        usage_tracker: Accumulates token/cost usage across all Generate stages.
        params: Named parameters from ``--arg`` flags and positional args.
        checkpoint_stages: Stage names restored from a checkpoint (shown as cached).
        injected_context: ``(label, content)`` pairs from ``.context()`` / ``.context_cmd()``.
        secrets: Resolved secret values keyed by name (masked in UI output).
        env: Pipeline-level environment variables from ``.env()``.
        retries: Total number of loop retries during this run.
        pipeline_skills: Skills applied to all Generate stages via ``.skills()``.
        stage_log: Detailed per-stage execution log for the run.
    """

    results: dict[str, StageResult] = field(default_factory=dict)
    usage_tracker: UsageTracker = field(default_factory=UsageTracker)
    stage_log: list[StageLogEntry] = field(default_factory=list)
    params: dict[str, Any] = field(default_factory=dict)
    checkpoint_stages: set[str] = field(default_factory=set)
    injected_context: list[tuple[str, str]] = field(default_factory=list)
    secrets: dict[str, str] = field(default_factory=dict)
    env: dict[str, str] = field(default_factory=dict)
    retries: int = 0
    pipeline_skills: list[Any] = field(default_factory=list)
    pipeline_profile: SessionProfile | None = None
    agent_provider: str = "claude-code"
    event_sink: Any = field(default_factory=_default_event_sink)
    input_responder: Any = field(default_factory=_default_input_responder)
    run_id: str = ""
    unit_id: str = "unit-0"
    run_controller: Any = None
    working_dir: str | None = None
    """Run working directory; relative stage paths resolve under it when set, else process cwd."""

    def get(self, stage_name: str) -> Any:
        """Get output from a previous stage."""
        return self.results[stage_name].output
